# Generated by Django 5.0.1 on 2024-01-18 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategories',
            options={'verbose_name_plural': 'Sub Categories'},
        ),
    ]
