# Generated by Django 5.0.1 on 2024-01-22 07:39

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=150)),
                ('username', models.CharField(default='', max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(default='./default/default_profile.webp', upload_to=users.models.CustomUser.image_upload_to)),
                ('instructor_title', models.CharField(blank=True, default='', max_length=200)),
                ('biografy', models.TextField(blank=True, default='', max_length=600)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, default='', max_length=200)),
                ('web_site_link', models.CharField(blank=True, default='', max_length=400)),
                ('twitter_link', models.CharField(blank=True, default='', max_length=400)),
                ('facebook_link', models.CharField(blank=True, default='', max_length=400)),
                ('linkin_link', models.CharField(blank=True, default='', max_length=400)),
                ('youtube_link', models.CharField(blank=True, default='', max_length=400)),
                ('paypal_account', models.CharField(blank=True, default='', max_length=400)),
                ('send_emails', models.BooleanField(default=False, verbose_name='Send me emails')),
                ('is_social_account_active', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_teach', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
                'ordering': ('-id',),
            },
        ),
    ]
