# Generated by Django 5.0.1 on 2024-01-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_social_account_active',
            field=models.BooleanField(default=True),
        ),
    ]
