# Generated by Django 5.0.1 on 2024-01-23 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('subcategories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subcategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='subcategories.subcategories'),
        ),
    ]
