# Generated by Django 5.0.1 on 2024-01-23 06:35

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=tinymce.models.HTMLField(max_length=800),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=tinymce.models.HTMLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='will_learn',
            field=tinymce.models.HTMLField(max_length=500),
        ),
    ]
