# Generated by Django 5.0.1 on 2024-01-23 07:33

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=tinymce.models.HTMLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=tinymce.models.HTMLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='course',
            name='will_learn',
            field=tinymce.models.HTMLField(max_length=2000),
        ),
    ]
