# Generated by Django 5.0.1 on 2024-01-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocourse',
            name='video',
            field=models.FileField(upload_to='<function VideoCourse.video_upload_to at 0x74b67aa27b00>'),
        ),
    ]
