# Generated by Django 5.0.1 on 2024-01-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_videocourse_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='video',
            field=models.FileField(upload_to='<function VideoCourse.video_upload_to at 0x7f4cfbfe3c40>'),
        ),
    ]
