# Generated by Django 5.0.1 on 2024-01-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_slug_alter_videocourse_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocourse',
            name='video',
            field=models.FileField(upload_to='<function VideoCourse.video_upload_to at 0x785633f2fba0>'),
        ),
    ]
