# Generated by Django 5.0.1 on 2024-01-17 01:41

import django.db.models.deletion
import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandsLogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(default='', upload_to=index.models.BrandsLogos.image_upload_to)),
            ],
            options={
                'verbose_name_plural': 'Brands Logos',
                'db_table': 'Brands_Logos',
            },
        ),
        migrations.AlterModelOptions(
            name='contentsection1',
            options={'verbose_name_plural': 'Content Section 1'},
        ),
        migrations.CreateModel(
            name='SelectLogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_logo', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='index.brandslogos')),
            ],
            options={
                'verbose_name_plural': 'Select Logos',
                'db_table': 'Select_Logos',
            },
        ),
    ]
