# Generated by Django 5.0.1 on 2024-01-17 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_brandslogos_alter_contentsection1_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandslogos',
            options={'verbose_name_plural': 'Upload Logos'},
        ),
    ]
